### ISSUE TITLE
request

### ISSUE THREAD

**Issue by fisherprice84** [akayn/demos#1]
hello friend do you have contact information?  thanks

**Comment by akayn** [comment]
you can send a direct msg to me on https://twitter.com/_akayn

**Comment by akayn** [comment]
or ask your Q here.

**Comment by fisherprice84** [comment]
Hi friend I dont use twitter but can make account if no Email. Thanks

**Comment by akayn** [comment]
so ask your Q here then... why so secret?

**Comment by fisherprice84** [comment]
Hi, wondering if available for freelance work this is why.  Thanks

**Comment by akayn** [comment]
nope i got a job good luck.
